### ISSUE TITLE
Criar diagrama de casos de uso

### ISSUE THREAD

**Issue by matheusbsilva** [desenho-2019-1/estudeplus#12]
- [X] Versão 1.0
- [x] Versão 2.0

Criar diagramas de caso de uso para exemplificar funcionalidades que compõe o sistema e como os usuários interagem com essas funcionalidades. Descrever atores, funcionalidades e relações.

**Comment by nukdown** [comment]
@ritzare  estou realizando um caso de uso do subsistema cadastro/validação de atores, alem de algumas funcionalidades do ator Monitor
