### ISSUE TITLE
Definição de Metodologia III: Código

### ISSUE THREAD

**Issue by victoralvesgomide** [desenho-2019-1/estudeplus#6]
É o artefato mínimo para essa apresentação. Ele vai gerar a compreensão para o grupo e para a professora do que estamos falando. Quebramos ele em 4 partes para podermos distribuir para as duplas.

Essa dupla será responsável por:
POLÍTICAS E PADRONIZAÇÃO DE CÓDIGO

- [x] Como e com que frequência surgem entregáveis de código?
- [x] Como e com que frequência surgem incrementos no software?
- [x] Quais as políticas do repositório? Como contribuir?
- [x] Qual a licença do software?
- [x] Como ocorre o versionamento? Há uma política de commits? Qual(is)?
- [x] Como ocorre o controle da padronização do código? São usadas ferramentas?
- [x] Como garantimos a qualidade do software? Como ocorrem os testes?
- [x] Integração contínua? Deploy contínuo?

PS: há um documento no Drive chamado "Pesquisa - OpenUP". Ele pode ajudar na definição desses tópicos. Como eu e Diego estamos fazendo pesquisas de metodologias, nós podemos ajudar também.

**Comment by matheusbsilva** [comment]
A padronização em relação a qualidade de código será definida junto com a(s) tecnologia(s) que serão utilizadas para implementar a solução
